apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: dilipmaurya/splitsettle-expense-service:latest  # note: your image name is express-service? but you used expense-service earlier, check
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ep-young-sun-ay45lka5-pooler.c-5.us-east-2.aws.neon.tech:5432/expense_db?sslmode=require&options=-c%20timezone=Asia/Kolkata"
            - name: SPRING_DATASOURCE_USERNAME
              value: "neondb_owner"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "npg_JLfWQdeu53wZ"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  selector:
    app: expense-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP