apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/dilipmaurya1586/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"   # if you deploy Kafka in K8s, else external
          # Also add email config if needed (SMTP)
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP